version: '3.8'

networks:
    laravel9-network:
        driver: bridge
volumes:
    laravel9-mysql:
        driver: local
    laravel9-redis:
        driver: local
    laravel9-php-vendor:
        driver: local
    laravel9-node-modules:
        driver: local

services:
    # App Server
    app:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP:-1000}'
        image: laravel9/sample/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER:-1000}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - 'laravel9-php-vendor:/var/www/html/vendor'
            - 'laravel9-node-modules:/var/www/html/node_modules'
        networks:
            - laravel9-network
        depends_on:
            - mysql
            - redis
    # Database
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'laravel9-mysql:/var/lib/mysql'
        command: --transaction-isolation=READ-COMMITTED
        networks:
            - laravel9-network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    # Session/Cache Storage
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'laravel9-redis:/data'
        networks:
            - laravel9-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    # DB GUI Client
    adminer:
        image: 'adminer:latest'
        container_name: adminer
        ports:
            - '${FORWARD_ADMINER_PORT:-8080}:8080'
        networks:
            - laravel9-network
    # SMTP / Mail Client
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - laravel9-network
